name: "CLA Assistant"
on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
     - opened
     - closed
     - synchronize

jobs:
  call-workflow:
    uses: dash0hq/.github/.github/workflows/cla.yaml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_PAT }}
